# Generated by Django 6.0.4 on 2026-04-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.FloatField(),
        ),
    ]
