# Generated by Django 6.0.4 on 2026-04-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chart', models.TextField()),
                ('roi_chart', models.TextField(blank=True, null=True)),
                ('total_pnl', models.FloatField()),
                ('win_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('ha_open', models.FloatField()),
                ('ha_high', models.FloatField()),
                ('ha_low', models.FloatField()),
                ('ha_close', models.FloatField()),
                ('ema_high', models.FloatField()),
                ('ema_low', models.FloatField()),
                ('signal', models.CharField(max_length=50, null=True)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('exit_type', models.CharField(blank=True, max_length=20, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
